main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: publications/
    weight: 20
  - name: News
    url: blog/
    weight: 30
  - name: Software
    url: software/
    weight: 40
  - name: People
    url: people/
    weight: 50
